name: Beta - Build and Deploy 

on:
  pull_request:
    types:
      - opened
    branches:
      - 'IOS-2808-Create-iOS-CI/CD'
  
jobs:
 prepare:
   name: Prepare information
   runs-on: ubuntu-latest
   outputs:
     version: "Develop"
     stage: "Beta"
     build_number: ${{ github.run_number }}
     changelog: ${{ steps.jira.outputs.summary }}
   steps:
   - name: Jira Login
     uses: atlassian/gajira-login@master
     env:

      JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        
   - name: Get Issues keys from all commits in current pull request
     id: github-issues
     uses: tangem/github-action@main
     with:
      github-token: ${{ secrets.GH_MOBILE_PAT}}
      pull-number: ${{ github.event.number }}
   
   - name: Jira Check Version
     id: jira-check-version
     uses: tangem/jira-action@master
     with:
       action: checkVersion
       project: IOS
       version: "Next Release"
       
   - name: Jira Create Version
     if: ${{ steps.jira-check-version.outputs.result == false }} 
     uses: tangem/jira-action@master
     with:
       action: createVersion
       project: IOS
       version: "Next Release"
       
   - name: Jira Set Version To Issues
     uses: tangem/jira-action@master
     with:
       action: setVersionToIssues
       project: IOS
       version: "Next Release"
       issues: ${{ steps.github-issues.outputs.issues }}
 build:
   name: Tangem Beta
   needs: prepare
   uses: tangem/actions/.github/workflows/build.yml@main
   with:
    stage: ${{needs.prepare.outputs.stage}}
    version: "${{needs.prepare.outputs.version}}"
    build_number: ${{needs.prepare.outputs.build_number}}
    path: "fastlane/builds/"
    filename: "Tangem-${{needs.prepare.outputs.stage}}-${{needs.prepare.outputs.version}}(${{needs.prepare.outputs.build_number}}).ipa"
   secrets:
    GH_MOBILE_PAT: ${{ secrets.GH_MOBILE_PAT}}
     
 deploy:
   name: Google Distribution
   needs: [prepare,build]
   uses: tangem/actions/.github/workflows/deploy.yml@main
   with:
    stage: ${{needs.prepare.outputs.stage}}
    version: "${{needs.prepare.outputs.version}}"
    build_number: ${{needs.prepare.outputs.build_number}}
    changelog: "${{needs.prepare.outputs.changelog}}"
    filename: "Tangem-${{needs.prepare.outputs.stage}}-${{needs.prepare.outputs.version}}(${{needs.prepare.outputs.build_number}}).ipa"
   secrets:
    FIREBASE_APP_ID: ${{ secrets.FIREBASE_IOS_ALPHA_ID}}
    FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN}}
   
 notification:
   name: Deploy Notification
   needs: [prepare,deploy]
   uses: tangem/actions/.github/workflows/notification.yml@main
   with: 
    channel: ${{vars.SLACK_CHANNEL_DEPLOYMENTS_IOS}}
    status: "success"
    app_name: ${{vars.APP_BETA}}
    deploy_to: ${{vars.DEPLOYMENT_GOOGLE_DISTRIBUTION}}
    version: ${{needs.prepare.outputs.version}}
    build_number: ${{needs.prepare.outputs.build_number}}
    changelog: ${{needs.prepare.outputs.changelog}}
   secrets:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
    
 error_notification:
   name: Error Notification
   if: failure()
   needs: [prepare,deploy]
   uses: tangem/actions/.github/workflows/notification.yml@main
   with: 
    channel: ${{vars.SLACK_CHANNEL_DEPLOYMENTS_IOS}}
    status: "error"
    app_name: ${{vars.APP_BETA}}
    deploy_to: ${{vars.DEPLOYMENT_GOOGLE_DISTRIBUTION}}
    version: ${{needs.prepare.outputs.version}}
    build_number: ${{needs.prepare.outputs.build_number}}
    changelog: ${{needs.prepare.outputs.changelog}}
   secrets:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
