name: Beta - Build and Deploy 

on:
  pull_request:
    branches: 
      - develop
    types:
      - open
      
  workflow_dispatch:
  
jobs:
 prepare:
   name: Prepare information
   runs-on: ubuntu-latest
   outputs:
     version: "Develop"
     build_number: ${{ github.run_number }}
     changelog: ${{ steps.jira.outputs.summary }}
   steps:
   - name: Jira Login
     uses: atlassian/gajira-login@master
     env:
       JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
       JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
       JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        
   - name: Get Issues keys from git commits
     id: github-issues
     uses: tangem/github-action@main
     with:
      github-token: ${{ secrets.GH_MOBILE_PAT}}
      pull-number: ${{ github.event.number }}

   # TEST
   - name: Output issues
     run: echo ${{ steps.github-issues.outputs.issues }}
   ### 
   
   - name: Jira Check Version
     id: jira-check-version
     uses: tangem/jira-action@master
     with:
       action: checkVersion
       project: IOS
       version: NextRelease
       
   - name: Jira Create Version
     if: ${{ steps.jira-check-version.outputs.result }} == false
     uses: tangem/jira-action@master
     with:
       action: createVersion
       project: IOS
       version: NextRelease
       
   - name: Jira Set Version To Issues
     uses: tangem/jira-action@master
     with:
       action: setVersionToIssues
       project: IOS
       version: NextRelease
       issues: ${{ steps.github-issues.outputs.issues }}
