name: Create Pull request from release branch to develop

on:
  push:
    branches:
      #- 'releases/**'
      - 'test/IOS-8785_ci_cd_create_release'  # TODO: Test only

jobs:
  trigger-reusable-workflow:
    uses: tangem-developments/actions/.github/workflows/create_pr_to_develop.yml@feature/AND-9998_create_pr_action  # TODO: Switch to main
    with:
      source_branch: ${{ github.ref_name }}
