name: Create release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version (i.e. 1.3.0)'
        default: '5.22' # TODO: Test only, remove
        required: true

jobs:
  prepare:
    name: Prepare Release
    uses: tangem-developments/actions/.github/workflows/prepare-release.yml@feature/IOS-8785_ci_cd_create_release
    with:
      versionName: ${{ inputs.versionName }}
      projectName: 'IOS'
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      GH_MOBILE_PAT: ${{ secrets.GH_MOBILE_PAT}}
      CREATE_RELEASE_BRANCH_KEY: ${{ secrets.CREATE_RELEASE_BRANCH_KEY }}
