name: Create release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 1.3.0)'
        default: '5.21' # TODO: Test only, remove
        required: true
      releaseType:  # TODO: Really used?
        type: choice
        description: 'Release or Hotfix'
        options:
          - release
          - hotfix
        default: 'release'
        required: true

jobs:
  prepare:
    name: Prepare Release
    uses: tangem/actions/.github/workflows/prepare-release.yml@feature/IOS-8741_ci_cd_notifications
    with:
      versionName: ${{ inputs.versionName }}
      releaseType: ${{ inputs.releaseType }}
    secrets:
      GH_MOBILE_PAT: ${{ secrets.GH_MOBILE_PAT}}
      JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      CREATE_RELEASE_BRANCH_KEY: '${{ secrets.CREATE_RELEASE_BRANCH_KEY }}'
