name: Tests

on:
  pull_request:
    branches: 
    - 'release/**'
    - 'develop'
    - 'master'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.GH_MOBILE_PAT }}
    
    - name: Cash bundler modules
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
        
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      
    - name: Cash cocoapods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
      
    - name: Pods install
      run: bundle exec pod install
      
    - name: Tests
      run: bundle exec fastlane test
      
    - name: Build notification
      if: failure()
      uses: adamkdean/simple-slack-notify@master
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_IOS }}
      with:
        channel: '#development-ios'
        text: 'Tangem tests #${{ github.run_number }} failed'
        color: 'danger'
        fields: |
          [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
      
